### ISSUE TITLE
Missing UserSummary and User properties

### ISSUE THREAD

**Issue by DAEINT-SM326** [MCUmbrella/Guilded4J#4]
The "avatar" and "banner" properties are missing from the UserSummary and User classes. The properties are both media-uri strings as defined in the [Guilded Bot API](https://www.guilded.gg/docs/api/members/ServerMemberSummary)

**Comment by MCUmbrella** [comment]
fixed in release [1.0-SNAPSHOT9](https://github.com/MCUmbrella/Guilded4J/releases/tag/1.0-SNAPSHOT9)
